# Generated by Django 3.1.1 on 2021-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gemeinden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.IntegerField()),
                ('gemeindekey', models.CharField(max_length=60)),
                ('gemeinde', models.CharField(max_length=255)),
                ('ewerbesteuer', models.IntegerField()),
            ],
        ),
    ]
