# Generated by Django 3.1.1 on 2021-04-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gemeinden',
            old_name='ewerbesteuer',
            new_name='gewerbesteuer',
        ),
    ]
